on: push
name: Slack Notification Demo
jobs:
  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ https://hooks.slack.com/services/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 }}
